
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Oct 31 20:27:54 CST 2023
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 35;
  public static final int POW = 33;
  public static final int STRING_LITERAL = 25;
  public static final int HECHIZOPRINCIPAL = 4;
  public static final int NUMERALITERAL = 26;
  public static final int COMMENT = 57;
  public static final int SI = 7;
  public static final int NUMERA = 16;
  public static final int GREATER = 39;
  public static final int DOTCOMMA = 55;
  public static final int MUTACION = 10;
  public static final int LESS = 37;
  public static final int MINUS = 29;
  public static final int AND = 46;
  public static final int NOT = 43;
  public static final int NUMERADECIMUS = 17;
  public static final int RUNAS = 20;
  public static final int SINO = 8;
  public static final int HECHIZO = 3;
  public static final int OR = 47;
  public static final int COMMA = 49;
  public static final int MIENTRAS = 9;
  public static final int RUNASTRING = 24;
  public static final int ARROBA = 44;
  public static final int NUMERADECIMUSLITERAL = 27;
  public static final int DOUBLEDOT = 56;
  public static final int DIV = 31;
  public static final int RECITA = 14;
  public static final int ESCRIBIO = 15;
  public static final int CONFRACTA = 13;
  public static final int PLUS = 28;
  public static final int ASSIGN = 54;
  public static final int LESSEQ = 38;
  public static final int NOMBREINGREDIENTE = 23;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 36;
  public static final int SINOX = 18;
  public static final int TRUE = 21;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int EQEQ = 41;
  public static final int RIVIERTO = 12;
  public static final int MOD = 32;
  public static final int PARARANGUS = 11;
  public static final int EQ = 34;
  public static final int RUNA = 19;
  public static final int GLOBALIO = 5;
  public static final int NOTC = 45;
  public static final int MULCOMMENTR = 59;
  public static final int ABRACADABRA = 2;
  public static final int SIAPARECE = 6;
  public static final int MULCOMMENTL = 58;
  public static final int SPACEGATO = 48;
  public static final int PARENR = 51;
  public static final int GREATEREQ = 40;
  public static final int DIFF = 42;
  public static final int KEYR = 53;
  public static final int FALSE = 22;
  public static final int PARENL = 50;
  public static final int KEYL = 52;
}

